version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server

  product-service:
    build: ./microservices/product-service
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - config-server
      - kafka

  cart-service:
    build: ./microservices/cart-service
    container_name: cart-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - config-server
      - kafka
      - product-service

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - product-service
      - cart-service